// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdRE8_IRGgT1VAVg-kQ-8C3KP1xhrnZmI',
    appId: '1:441400253964:web:b86f0ce787623e17721829',
    messagingSenderId: '441400253964',
    projectId: 'kindi-21946',
    authDomain: 'kindi-21946.firebaseapp.com',
    storageBucket: 'kindi-21946.firebasestorage.app',
    measurementId: 'G-MT9B8FDKGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnCDOJKJlxSZU90IlFXUstPJDF6b40taU',
    appId: '1:441400253964:android:2c48eafc04eecd57721829',
    messagingSenderId: '441400253964',
    projectId: 'kindi-21946',
    storageBucket: 'kindi-21946.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXoys6g9LBDAHt8ukWfuIIrZsWv-pwn_k',
    appId: '1:441400253964:ios:d2247a5f339bf49f721829',
    messagingSenderId: '441400253964',
    projectId: 'kindi-21946',
    storageBucket: 'kindi-21946.firebasestorage.app',
    iosBundleId: 'com.example.kindi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXoys6g9LBDAHt8ukWfuIIrZsWv-pwn_k',
    appId: '1:441400253964:ios:d2247a5f339bf49f721829',
    messagingSenderId: '441400253964',
    projectId: 'kindi-21946',
    storageBucket: 'kindi-21946.firebasestorage.app',
    iosBundleId: 'com.example.kindi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdRE8_IRGgT1VAVg-kQ-8C3KP1xhrnZmI',
    appId: '1:441400253964:web:0f8826c54f725aa4721829',
    messagingSenderId: '441400253964',
    projectId: 'kindi-21946',
    authDomain: 'kindi-21946.firebaseapp.com',
    storageBucket: 'kindi-21946.firebasestorage.app',
    measurementId: 'G-DBNPTMDMJW',
  );
}
